name: hym_score_flutter_pro
description: "A new Flutter project."
# This project is not intended for publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0  # Updated to match the downgraded Flutter version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.8  # Updated to match flutter_test dependency
  material_color_utilities: ^0.11.1  # Updated to match flutter_test dependency
  vm_service: ^15.0.1  # Updated to match flutter_test dependency
  shared_preferences: ^2.5.2
  path_provider: ^2.0.15
  syncfusion_flutter_charts: ^22.2.8
  csv: ^5.0.0 
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  share_plus: ^7.0.2  # Use the latest stable version
  fl_chart: ^0.70.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypt: ^5.0.1
  flutter_secure_storage: ^9.0.0
  file_saver: ^0.2.7
  mime: ^1.0.4
  pdf: ^3.10.4
  printing: ^5.11.0
  model_viewer_plus: ^1.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6

dependency_overrides:
  cupertino_icons: ^1.0.5
  async: ^2.13.0
  fake_async: ^1.3.3
  vm_service: 14.3.1  # ✅ Force Flutter to use compatible version
  material_color_utilities: 0.11.1  # ✅ Force Flutter to use compatible version
  leak_tracker: ^10.0.8  # Updated to match flutter_test dependency
flutter:
  uses-material-design: true

  assets:
    - assets/body_memoji.png